### ISSUE TITLE
[Canada] Incorrect highway classifications

### ISSUE THREAD

**Issue by mvexel** [TelenavMapping/mapping-projects#10]
This was called out on `talk-ca`:

> [...] wildly incorrect highway classifications [...]

No specific examples given.

**Comment by inah-telenav** [comment]
Regarding this issue, we use the guidelines from the wiki page: https://wiki.openstreetmap.org/wiki/Key:highway

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#6
