### ISSUE TITLE
Suggestion: integrate changeset discussion with Github tickets

### ISSUE THREAD

**Issue by scruss** [TelenavMapping/mapping-projects#12]
As I noted on [Talk-ca](https://lists.openstreetmap.org/pipermail/talk-ca/2017-April/007846.html), OSM provides the changeset discussion mechanism for resolving contentious edits. There's currently no link between issues raised in changesets and this restricted-membership forum.

**Comment by mvexel** [comment]
My comment on talk-ca: 

> Yes, if you ask me, changeset comments are (and will stay) the #1 place to discuss mapping issues. If a mapper continues to do questionable edits, the public channels like this mailing list are a good place to go to. 
>
> To look at recent changeset comments, I use Pascal Neis’s tool. If you haven’t seen that yet you should definitely check it out: http://resultmaps.neis-one.org/osm-discussions?c=Canada#5/48.805/-99.802 
>
> So like I said in my other response just now, GitHub issues are secondary to that, more like a convenient way for us to track and for  mappers to see what projects we are proposing and working on, and if you happen to have a Github account you can also comment. 
> 
> Sorry that was not more clear from the outset.

**Comment by mvexel** [comment]
Closing here, but feel free to re-open or let me know if you have remaining concerns related to this, @scruss
