### ISSUE TITLE
Oakland County roads

### ISSUE THREAD

**Issue by mvexel** [TelenavMapping/mapping-projects#14]
[Oakland County Roads](http://accessoakland.oakgov.com/datasets/oc-roads) would be useful for #4 and #3. The license is:

> Public records or GIS Data that is published on the Oakland County Access Oakland Open Data Portal/website (“Open Data”) is provided to You, subject to the terms and conditions contained in this Terms of Use Agreement (“Agreement”) and all applicable laws and regulations, including laws and regulations governing copyrights, patents, trade secrets, servicemarks and trademarks.For the purposes of this Agreement, the County of Oakland shall be referred to as the "County", and you, including any of your employees or agents, will be referred to as "You" (including the possessive "Your"). This Agreement applies regardless of: 1) the method You use to access the Open Data; 2) the media on which the Open Data is presented, stored or made available to You; and 3) the services provided by the County to assist You in obtaining the Open Data.
> 
> 1. BY ACCESSING, DOWNLOADING, VIEWING, OR OTHERWISE USING THE OPEN DATA PORTAL/WEBSITE OR THE CONTENT/OPEN DATA CONTAINED THEREIN, YOU ACCEPT, WITHOUT LIMITATION OR QUALIFICATION, ALL OF THE TERMS AND CONDITIONS IN THIS AGREEMENT.
> 
> 2. The County reserves the right to change this Agreement at any time without notice.  Changes to this Agreement will only apply to future uses of the Open Data.You may check for updates to this Agreement by clicking on the "Terms of Use” Agreement hyper-text on the Open Data Portal/website.  Your continued use of the Open Data Portal/website after updates to this Agreement have been posted will constitute Your agreement to those updates to this Agreement.The County additionally reserves the right to modify or discontinue, at any time, any Open Data or the Open Data Portal/website, without notice or liability.
> 
> 3. Use of Open Data. You may retrieve, download, copy, modify, translate, adapt, distribute, sort, search, and reuse Open Data for any lawful purpose. You shall not use, share or distribute Open Data for any unlawful purpose or act. You shall not reproduce any trademark or service mark on the Open Data Portal/website or in Open Data without the express written permission of the respective mark owner. Unauthorized attempts to upload information to, modify, or cause damage to the Open Data Portal/website is prohibited.
> 
> 4. Indemnification. You agree to indemnify, defend, and hold harmless the County, and the County's respective officials, agencies, officers, subsidiaries, employees, licensors and agents, from and against any and all liability, loss, claims, damages, costs and/or actions (including attorneys' fees) based upon or arising out of any breach by You of Your obligations under this Agreement including, but not limited to, any claim or cause of action, of any type, that may be or is alleged to have arisen out of Your use of the Open Data.  Notwithstanding Your indemnification obligation, the County reserves the right at its sole discretion to defend any such claim and You agree to provide the County with such reasonable cooperation and information as the County may request.
> 
> 5. DISCLAIMER OF WARRANTY AND LIMITATION OF LIABILITY: WHILE THE COUNTY USES REASONABLE EFFORTS TO PROVIDE ACCURATE AND UP TO DATE OPEN DATA, SOME OF THE INFORMATION PROVIDED IS GATHERED BY THIRD PARTIES AND HAS NOT BEEN INDEPENDENTLY VERIFIED BY THE COUNTY.YOU AGREE THAT ALL USE OF THE OPEN DATA IS AT YOUR OWN RISK, AND THAT THE COUNTY WILL NOT BE HELD LIABLE FOR ANY ERRORS OR OMISSIONS CONTAINED IN THE OPEN DATA OR FOR THE COUNTY'S SERVICES IN MAKING THE OPEN DATA AVAILABLE TO YOU.
> 
> 6. THE OPEN DATA IS PROVIDED ON AN "AS IS" AND “AS AVAILABLE” BASIS. THE COUNTY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS AND IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF ACCURACY, RELIABILITY, TITLE, MERCHANTABILITY, NON INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM MALWARE. THE COUNTY DOES NOT REPRESENT OR WARRANT THAT ACCESS TO THE OPEN DATA WILL BE UNINTERRUPTED OR THAT THERE WILL BE NO FAILURES, ERRORS OR OMISSIONS OR LOSS OF TRANSMITTED INFORMATION.
> 
> 7. THE OPEN DATA IS PROVIDED TO THE PUBLIC FREE OF CHARGE TO FOSTER CIVIC ENGAGEMENT THROUGH DATA SHARING, INCREASE THE TRUST AND IMPROVE THE RELATIONSHIP BETWEEN CITIZENS, BUSINESS, AND GOVERNMENT AGENCIES, AND ENABLE BUSINESSES AND OTHER CITIZEN ENTERPRISES TO MAKE USE OF GOVERNMENT DATA TO PROMOTE ECONOMIC DEVELOPMENT AND INCREASE INVESTMENT. THIS AGREEMENT DOES NOT, AND IS NOT INTENDED TO IMPAIR, DIVEST, DELETE, OR CONTRAVENE ANY CONSTITUTIONAL, STATUTORY, OR OTHER LEGAL RIGHT, PRIVILEGE, POWER, OBLIGATION, DUTY, OR IMMUNITY OF THE COUNTY.
> 
> 8. IN NO EVENT SHALL THE COUNTY BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION IN CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OF OPEN DATA AVAILABLE FROM THE COUNTY.
> 
> 9. THE INFORMATION, DOCUMENTS AND RELATED GRAPHICS PUBLISHED IN THE OPEN DATA OR ON THE OPEN DATA PORTAL/WEBSITE COULD INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS.CHANGES ARE PERIODICALLY MADE TO THE INFORMATION.  THE COUNTY MAY MAKE IMPROVEMENTS AND/OR CHANGES TO THE OPEN DATA OR THE OPEN DATA PORTAL/WEBSITE AT ANY TIME.
> 
> 10.  THE OPEN DATA PORTAL/WEBSITE MAY CONTAIN LINKS TO OTHER WEBSITES. THE COUNTY DOES NOT ENDORSE, ENSURE THE ACCURACY OF, OR VOUCH FOR THE SAFETY AND PRIVACY OF ANY LINKED OR OTHER WEBSITES. THE COUNTY DOES NOT ASSUME ANY RESPONSIBILITY FOR ANY LINKED OR OTHER WEBSITES OR THE CONTENT FOUND ON THOSE WEBSITES. YOU ASSUME ALL RISK FOR USING LINKED OR OTHER WEBSITES .  IT IS YOUR SOLE RESPONSIBILITY TO EVALUATE THE SAFETY, PRIVACY, CONTENT AND USEFULNESS OF LINKED OR OTHER WEBSITES.
> 
> 11.  BY USING THE OPEN DATA PORTAL/WEBSITE, THIRD PARTIES MAY PLACE A COOKIE ON YOUR COMPUTER. THE COUNTY IS NOT RESPONSIBLE FOR ANY COOKIE PLACED ON YOUR COMPUTER BY A THIRD PARTY.
> 
> 12.  Governing Law/Consent to Jurisdiction and Venue. Any claim or action arising from or relating to this Agreement, the Open Data, or the Open Data Portal/website shall be governed, interpreted, and enforced by the laws of the State of Michigan, without regard to Michigan’s conflict of law provisions to the extent that those principles or rules would require or permit the application of the laws of any jurisdiction other than those of the State of Michigan. Except as otherwise required by law or court rule, any action brought to enforce, interpret, or decide any claim arising under or related to this Agreement, the Open Data, or the Open Data Portal/website shall be brought in the 6th Judicial Circuit Court of the State of Michigan, the 50th District Court of the State of Michigan, or the United States District Court for the Eastern District of Michigan, Southern Division, as dictated by the applicable jurisdiction of the court. Except as otherwise required by law or court rule, venue is proper in the courts set forth above.
> 
> 13.  Entire Agreement. This Agreement constitutes a valid and binding agreement between You and the County. This Agreement represents the entire agreement between You and the County, and supersedes any and all other communications, prior, contemporaneous or subsequent.

**Comment by gabrielas-telenav** [comment]
Emailed LWG.

**Comment by mvexel** [comment]
Response from LWG: 

> Any terms or licence that requires us to indemnify etc (as required in in (4)) the data source will not be compatible with the way OSM works and it doesn't make sense to investigate such a licence any further. Sorry.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#19
