### ISSUE TITLE
USA – Detroit – Turn Restriction

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#16]
## Description
In this project, we will map turn restrictions in Detroit, Michigan area, and we will focus on adding missing restrictions as well as improving the existing data in OSM.
## How to map
We will follow the mapping scheme that is already used by OSM community as it is described on this page:
* http://wiki.openstreetmap.org/wiki/Relation:restriction 

We will also follow the rules that are already used in Detroit for turn restriction mapping:

![1](https://cloud.githubusercontent.com/assets/24428741/26090993/049a894e-3a11-11e7-8e9b-bc3747745ff8.png)

We’ll also keep in mind to add any other useful information that are related to turn restrictions (e.g.: oneways, roads under construction etc.)
We will use OpenStreetCam and Mapillary as sources.

## Who will be involved
[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team) 

## See also:
* https://www.mapbox.com/mapping/mapping-for-navigation/adding-turn-restrictions/  
* http://blog.improve-osm.org/en/2016/03/turn-restrictions-a-vital-part-of-any-routing-system/

**Comment by manuelab-telenav** [comment]
We worked on this issue since middle of May and we are still in progress. We succeeded to review all existing restriction, and we corrected them if it was necessary. Also, we used OSC images to add new restrictions in Detroit area.
We focused on the three most important counties: Wayne, Oakland and Macomb, but we also edited in the five other 5 counties near Detroit: Monroe, Genesee, Washtenaw, Livingston and Lenawee. 

### Breakdown stats for adding turn restrictions in Detroit area:
![image](https://user-images.githubusercontent.com/24428741/28367474-c3991684-6c99-11e7-87c8-3093e6a30e2b.png)

Here’s how the number of turn restrictions has increased during the project:

![image](https://user-images.githubusercontent.com/24428741/28367515-ea639a64-6c99-11e7-9a0f-7208839ecd46.png)

Here you can see all the areas where we edited turn restrictions:

![image](https://user-images.githubusercontent.com/24428741/28367489-d00a6512-6c99-11e7-84c5-2722cd887209.png)

Here’s how many turn restrictions we added per county during the project:

![image](https://user-images.githubusercontent.com/24428741/28367591-2d3962d8-6c9a-11e7-9116-2385ed8b24e9.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#17
