### ISSUE TITLE
[US] El Paso-Las Cruces-TX-NM - Roads dataset 

### ISSUE THREAD

**Issue by arming-telenav** [TelenavMapping/mapping-projects#162]
We are considering using this dataset for our future edits in El Paso-Las Cruces-TX-NM metro area:

El Paso [roads](https://tnris.org/data-download/#!/county/El%20Paso) - TxDOT Roadway shapefile.

License type - Public domain

Sent email to data owner to check license compatibility. 

![image](https://user-images.githubusercontent.com/24649532/44025561-2833417c-9ef9-11e8-9e51-194bd3a5ccba.png)

**Comment by mihaii-telenav** [comment]
The local data file was processed with [Cygnus](http://cygnus.improve-osm.org/add?5) resulting 57.8 mi of roads that did not have names in OSM but had names in the local data file. These roads have been reviewed, and for 24%% (14 mi) the names have been added. The remaining 76% (43.8 mi) consisted of false positives, or cases where local data was inconclusive, and have been skipped.
