### ISSUE TITLE
USA - Detroit - Cartographic feature validation

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#17]
## Description
In this project we will digitize different cartographic features in Detroit, Michigan area, to improve the visual quality of the map. We will improve the road network in the central part of Detroit and in the same time we will focus to add parking lots, parking aisles, major buildings geometry, water bodies, specific land use areas (important parks, forests, cemeteries, industrial areas, playgrounds and sport grounds, quarries, places of worship, wetlands, vineyards, etc.). In the end we will do a quality assurance process which will include the validation tool from JOSM and we will fix different issues in the central area of Detroit.

![f2](https://cloud.githubusercontent.com/assets/24428741/26095980/55b28acc-3a28-11e7-9d57-7a7a600cd26a.JPG)

![1](https://cloud.githubusercontent.com/assets/24428741/26095637/f90c76c6-3a26-11e7-9dbd-27f4cb29f58e.jpg)
![2](https://cloud.githubusercontent.com/assets/24428741/26095644/000ed1c6-3a27-11e7-9460-57feb65148af.jpg)

## How to map
We will follow the mapping rules as it is described on these pages:
* http://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle
* http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking
* http://wiki.openstreetmap.org/wiki/Key:building
* http://wiki.openstreetmap.org/wiki/Key:water
* http://wiki.openstreetmap.org/wiki/Key:landuse

## Sources:
* Satellite imagery: Bing, Mapbox, Digital Globe
* Government data: TIGER 
* Improve OSM - Missing Roads
* Street-level imagery: OpenStreetCam, Mapillary
* Validation tool from JOSM

## Who will be involved
[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team) with the following users: marianp_telenav, andreis_telenav.

## See also
* https://www.mapbox.com/mapping/mapping-common-features/ 
* https://www.mapbox.com/mapping/mapping-with-josm/ 
* https://www.mapbox.com/mapping/becoming-a-power-mapper/advanced-mapping-guide/
* https://www.mapbox.com/mapping/becoming-a-power-mapper/fixing-common-mapping-issues/

**Comment by manuelab-telenav** [comment]
We worked on this issue in the middle of May and we digitized different cartographic features in Detroit, to improve the visual quality of the map, using also OpenStreetCam photos.
We focused on the three most important counties: Wayne, Oakland and Macomb. In the end we've done a quality assurance process which included the validation tool from JOSM and other tools, to fix different issues in the central area of Detroit.

### Breakdown stats for adding new cartographic features in Detroit area:

![metrics_carto_features_detroit_may_2017](https://user-images.githubusercontent.com/24428741/28416929-af2f8ba4-6d5e-11e7-91c1-c0d6e65ba53c.jpg)

In this heatmap you can see all the areas where we added new cartographic features:

![heat_map_carto_features_detroit_may_2017](https://user-images.githubusercontent.com/24428741/28416940-c6927798-6d5e-11e7-8d4c-17311250085e.jpg)

Here you can see two comparisons between different areas, before and after our edits:
![before-after_01](https://user-images.githubusercontent.com/24428741/28416949-d5c8a98a-6d5e-11e7-85e2-bace890493b1.gif)
![before-after_02](https://user-images.githubusercontent.com/24428741/28416962-e0d1f926-6d5e-11e7-8da2-293ee7ae344f.gif)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#16
