### ISSUE TITLE
USA – Detroit - Traffic signals

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#19]
In this project we will map traffic signals in Detroit, Michigan area and we will focus on adding missing traffic signals as well as improving the existing data in OSM.

## How to map
We will follow the mapping scheme that is already used in the United States as it is described on this page: http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals
## Tags that we use for mapping:
* Traffic signals –> **highway=traffic_signal**

We’ll also keep in mind to add any other useful information that we have for the mapped signs (ex.: turn restrictions).
## Sources:
* Local data: Traffic Signals (https://data.detroitmi.gov/Transportation/Traffic-Signals/dkav-a7rb)
* Satellite imagery: Bing
* Street level imagery: Open Street Cam, Mapillary
## Want to help?
We filtered out the traffic signals and stop signs that were already in OSM but there is still a significant amount of data that can be added in OSM (912 cases for traffic signals and 8755 for stop signs). Due to this, we thought about creating a MapRoulette challenge.

So, given the available data that we found, we created two challenges:
* Traffic Signals - http://www.maproulette.org/view/2593 
* Stop Signs - http://www.maproulette.org/view/2564 
## See also:
* http://blog.improve-osm.org/en/2017/06/mapping-traffic-signals-and-stop-signs-using-maproulette/

**Comment by mvexel** [comment]
The default zoom level is too low -- you have to zoom in a few times to get a decent zoom level to click 'edit'. Could you fix please? 👍

**Comment by manuelab-telenav** [comment]
We worked on this issue since the middle of June and we are still in progress. We succeeded to review all existing traffic signals, and we corrected them if it was necessary. Also, we used OSC images to add new traffic signals in Detroit area.
We focused on 3 most important counties: Wayne, Oakland and Macomb.

### Breakdown stats for correcting existing traffic signals in Detroit area:
![image](https://user-images.githubusercontent.com/24428741/28368825-631f3bb2-6c9e-11e7-9443-a9956c7e8ee9.png)

Here you can see all the areas where we validated traffic signals:
![image](https://user-images.githubusercontent.com/24428741/28368847-79275138-6c9e-11e7-9685-e9889e753a41.png)

### Breakdown stats for adding new traffic signals in Detroit area:
![image](https://user-images.githubusercontent.com/24428741/28368872-8e745aae-6c9e-11e7-823b-e55827752a6c.png)

Here’s how the number of traffic signals has increased during the project:

![image](https://user-images.githubusercontent.com/24428741/28368960-caa5e894-6c9e-11e7-8873-f3a32b695785.png)

This map shows the area where we added traffic signals from local data:

![image](https://user-images.githubusercontent.com/24428741/28368990-dfc33588-6c9e-11e7-80c4-3cb2c02e0cb8.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#15
