### ISSUE TITLE
USA - Detroit - One ways

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#2]
## Description
This project is designed to improve the quality of OSM by adding oneways in the Detroit, Michigan area. 

## How to map
![oneway](https://cloud.githubusercontent.com/assets/24428741/24803042/a3f26660-1bb2-11e7-9b2a-2391e45facaf.JPG)

Will add [oneway=yes](http://wiki.openstreetmap.org/wiki/Key:oneway) tag after checking the direction of the road with the following sources:
* **Aerial Imagery**: Bing, Mapbox, NAIP
* **Street level imagery**: OSC, Mapillary
* **Improve OSM** - Traffic Flow Direction

#
**NOTES** 
* Pay attention to the direction of the way! Before adding the **oneway=yes** tag, make sure that the direction of digitization matches the direction of the oneway. If not, press "R" to reverse the direction and only after add the oneway=yes tag.
* For roundabouts, the **oneway=yes** is implied, so it is not necessary to add it explictly.

## Who will be involved
[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team) 

## See also
* http://wiki.openstreetmap.org/wiki/Key:oneway
* http://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout

**Comment by hoream-telenav** [comment]
We added from ImproveOSM 22.22 miles of new one way roads.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#23
