### ISSUE TITLE
USA - Detroit - Barrier editing

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#20]
## Introduction
A barrier is a physical structure which blocks or impedes movement. The barrier tag only covers on-the-ground barriers.
There are many types of barriers. See them listed [here](http://wiki.openstreetmap.org/wiki/Key:barrier)

![image](https://user-images.githubusercontent.com/24428741/28364701-46f69440-6c8e-11e7-8739-190dbbba96cc.png)

## How to map:
* add the tag barrier=gate to the node where the gate is

Our editing purpose was to add the following types of barriers in 3 counties from Detroit area: Wayne, Macomb and Oakland, and also to review the existing ones.
![image](https://user-images.githubusercontent.com/24428741/28364479-47769380-6c8d-11e7-9672-4e802d493560.png)

## Who will be involved?

[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team)

**Comment by hoream-telenav** [comment]
We added 370 barriers.
**Heatmap**
![image](https://user-images.githubusercontent.com/25051328/42216265-e70c99d6-7ec9-11e8-9912-4f38aa0b0649.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#14
