### ISSUE TITLE
USA - Detroit - Speed limit

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#21]
## Description
This project is designed to improve the quality of OSM by adding and updating speed limits on motorways, trunks, primary, secondary, tertiary and unclassified roads in Detroit, Michigan.

![1](https://user-images.githubusercontent.com/24428741/28416240-e2014822-6d5b-11e7-9e49-bc15e290f4b6.png)

## How to map
For editing speed limits we will use JOSM and a map paint style specially created to highlight the ‘maxspeed’ tag of each way.
We will use the ‘maxspeed=*’, ‘maxspeed:forward=*’, ‘maxspeed:backward=*’ tags to add the speed limits on every way.

Speed limits are often shown on a sign at the start of the restricted section. A posted speed limit may only apply to that road or to all roads beyond the sign. Some places provide an additional "speed zone ahead" before the restriction. Also, speed limit reminder signs may appear at regular intervals, painted on the road surface.

For adding speed limits, we are using the newest trips from Open Street Cam. We review the available trips looking for  speed limit signs, then we add or update the speed limits tags starting from the point where the signs appear. 

In situations where the road signs are near an intersection the starting/ending point of the speed limit rule will be starting/ending from/in the intersection node.

![2](https://user-images.githubusercontent.com/24428741/28416297-1ed2599e-6d5c-11e7-8c03-5f21533a6ce2.png)

For two-way streets, where we have different lane values for each way, we use the ‘maxspeed:forward=*’ and the ‘maxspeed:backward=*’ tags to be able to map both numeric values. 
Forward means the direction in which the way is drawn in Open Street Map, while backward means the opposite direction. 

## Sources
* Aerial Imagery: Bing, Mapbox, NAIP, Digital Globe
* Street level imagery: OSC, Mapillary

## Who will be involved
[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team)

**Comment by hoream-telenav** [comment]
We added 1503 miles of speed limit usinc OSC and Mapillary photos.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#13
