### ISSUE TITLE
[Canada Maintenance] - Road name and road geometry

### ISSUE THREAD

**Issue by inah-telenav** [TelenavMapping/mapping-projects#22]
We are considering using these database for our future edits in Canada

* [Census](http://open.canada.ca/en/open-government-licence-canada)

The license needs to be checked.
This license is OGL 2.0

**Comment by inah-telenav** [comment]
Reading the issue, we came to the conclusion that Geobase contains Census: https://en.wikipedia.org/wiki/GeoBase_(geospatial_data)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#5
