### ISSUE TITLE
Dealing with different sources of data

### ISSUE THREAD

**Issue by lacram-telenav** [TelenavMapping/mapping-projects#25]
In February 2017, among other edits, we added 5 residential roads in La Prairie area, Canada (see image below). We used Canvec and Geobase Roads as a source. Recently, a colleague from the community raised the problem that those roads do not exist in the reality because the area is under protection. Therefore, we checked again the sources that we have to confirm the absence of the roads: Bing, Mapbox, Canvec, Geobase Roads. As the roads appear on a couple of sources and on other not, we decided to search for more information. As a conclusion, those roads do not exist because the local habitats are protected by law and the road construction is forbidden. Our next step is to delete those roads and make sure that next time we will double check the sources we have when we add information to OSM.

If you want to check the area, here are the **coordinates**: 45.3940389, -73.474383. Also, the **way IDs** of the roads are: 472613767, 13470677, 472613765, 472613760, 472613763.

![imgpsh_fullsize](https://user-images.githubusercontent.com/25051349/30546655-f049db74-9c95-11e7-83a0-82e497871099.png)

**Comment by mvexel** [comment]
My comments in talk-ca:

Hi all, 

> Allow me to respond in English...Sorry..
> Thanks for pointing out the problem with the non-existing roads. We did some additional research ourselves as well after your report and concluded the same thing. Checking two sources in this case proved to be not enough, and I will make sure we proceed even more carefully when the evidence is inconclusive...I am really sorry about this.
> I have deleted the ways in question, https://www.openstreetmap.org/changeset/52154252 
> We will take extra care in the future that the source list in the changeset really does reflect all the sources we used. (In this case, there was no OSC imagery available).
> 

Two follow up actions @lacram-telenav:

1. Implement stricter decision rules when sources are inconclusive.
2. Implement consistently correct use of `source` tag in changeset comments.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#2
