### ISSUE TITLE
Signpost editing in Maricopa and Pinal counties, Arizona

### ISSUE THREAD

**Issue by hoream-telenav** [TelenavMapping/mapping-projects#26]
**Description:**
For this task we will map signpost in Maricopa and Pinal county, Arizona. Our main focus is adding new signposts but we will also improve consistency in the existing data.
![image](https://user-images.githubusercontent.com/25051328/30864611-ccbdeb62-a2dc-11e7-84ba-7897f3da6853.png)
**How to map:**
We will follow the signpost mapping scheme that is already in wide use in North America:
The exit number goes on the junction node as ref on the motorway_junction node.
The destination, destination:street, destination:ref, destination:symbol go on the first _link way after the motorway_junction node.
As sources for mapping we will use OpenStreetCam and Mapillary.
**Who will be involved?**
Telenav mapping team with the following users: inah_telenav, oanac_telenav
**See also:**

- https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/

- http://wiki.openstreetmap.org/wiki/Exit_Info

- http://wiki.openstreetmap.org/wiki/Key:destination

**Comment by mihaii-telenav** [comment]
The signpost task has been completed. Please find below some conclusions.

Overall, this task was split into two processes - the editing part and the QA part.

For the **editing** part, we have used the following workflow:

1. we've extracted all the motorway and trunk links and distributed the output among the team members
2. using street-level imagery, **OSC** and **Mapillary**, we've reviewed the output and checked for the following:
- for **nodes**, we made sure that the **motorway junctions** had the **highway=motorway_junction** and **ref=*** (or **noref=yes**) tags. If the node had the **exit_to** tag, **we did not remove it**.
- for **ways**, we checked and added **destination**, **destination:street**, **destination:ref,** **destination:ref:to** and **destination:symbol**. We added these tags on the first motorway_link way after the motorway_junction node, but at the same time, if the following ways had previously added signpost information, we made sure that it is consistent along the whole length of the motorway_link. Also, if we found cases where there was a street name in the **destination** tag, **we did not modify it** to destination:street.
 
For the **QA** part, we used PostGIS queries and checked the following:

- motorway_junction without ref, noref, ref:left or ref:right and added them using OSC or Mapillary
- motorway_junction with motorway_link specific tags - destination, destination:street, destination:ref, destination:ref:to and destination:symbol - in these cases we've moved the information on the motorway_link
- motorway_link with ref tag - in these cases we've removed the ref tag
- look for weird characters in the destination tags

Here's an overview of the evolution of the signposts between Sept 2017 and Jan 2018:

![image](https://user-images.githubusercontent.com/20751382/34868843-c86930a2-f78d-11e7-818f-c5b05f4e5721.png)

Heatmap overview of our edits:

![image](https://user-images.githubusercontent.com/20751382/34868891-e51765ac-f78d-11e7-802d-1e482a9d7042.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#12
