### ISSUE TITLE
Signpost editing in Canada

### ISSUE THREAD

**Issue by lacram-telenav** [TelenavMapping/mapping-projects#27]
While editing in Fredericton, we came across signposts with English and French information regarding the **road type**. This information is added to OSM using the **destination:street** tag (see example below). We think that it would be more appropriate to separate this information into two tags so that the example below would become **destination:street:en**=Regent Street South and **destination:street:fr**=Rue Regent Sud. Before doing any change, we will consult with the community to see if it agrees with this proposal. 

One advantage of using separate tags is that the OSM data is more clear and structured when using specific language names. Road name is an example of map feature for which there were successfully used specific tags (e.g.name:fr, name:en, name:de).

If you want to check the signpost from the image below, here are the **coordinates**: 
45.9394012, -66.6664205.

![sign](https://user-images.githubusercontent.com/25051349/30909707-ce8a6a7a-a38a-11e7-96b8-d78df0af0668.PNG)

**Comment by mvexel** [comment]
Emailing the top contributors with this message:

> Hi, 
> 
> I am getting in touch because you may have done a lot of editing in New Brunswick, according to http://resultmaps.neis-one.org/oooc. I work for Telenav in a team of more than 20 mappers. Our goal is to improve the map by making it more suitable for navigation. New Brunswick is one of the areas we are working in, and we have a question about best mapping practices in the province. We are seeking guidance from local mappers like yourself.
> 
> We are encountering destination signs (signposts) that have bilingual names on them. You can see an example on the Github issue page we created for this topic: https://github.com/TelenavMapping/mapping-projects/issues/27 .
> 
> We would propose to map this as `destination:street:en=Regent Street South` and `destination:street:fr=Rue Regent Sud` in order to properly separate the languages.
> 
> Do you agree this would be an appropriate way to map these situations? Do you have any suggestions? Please feel free to contact me or any of my colleagues at any time through OSM message. Thanks!
> 
> Martijn

Sending to: 

- em132 - http://www.openstreetmap.org/user/em132
- hhcfw - http://www.openstreetmap.org/user/hhcfw
- breau - http://www.openstreetmap.org/user/breau
- the506 - http://www.openstreetmap.org/user/the506
- berniejconnors - http://www.openstreetmap.org/user/berniejconnors
- jacques99 - http://www.openstreetmap.org/user/jacques99
- Dascombe - http://www.openstreetmap.org/user/Dascombe
- Freeballer - http://www.openstreetmap.org/user/Freeballer
- 56lz2slow - http://www.openstreetmap.org/user/56lz2slow
- julien bourque - http://www.openstreetmap.org/user/julien%20bourque
- ingalls – http://www.openstreetmap.org/user/ingalls

**Comment by mvexel** [comment]
After another round of comments, edited these wiki sections to reflect this consensus:

-
 https://wiki.openstreetmap.org/wiki/Proposed_features/Destination_details#destination:street_.2F_destination:street:.3Clanguage_code.3E
- https://wiki.openstreetmap.org/wiki/Key:destination#Examples

**Comment by lacram-telenav** [comment]
We decided to keep both ways of mapping the bilingual signposts: the way the community maps them (destination:street:lang:en/destination:street:lang:fr) and the way we map them (destination:street:en/destination:street:fr).

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#4
