### ISSUE TITLE
Center turn lanes mapping

### ISSUE THREAD

**Issue by mvexel** [TelenavMapping/mapping-projects#28]
@alinan-telenav / @gabrielas-telenav / @petrar-telenav and I had a discussion about center turn lane mapping. Conclusions and community RFC posted: [OSM diary](https://www.openstreetmap.org/user/mvexel/diary/42432) / [talk-us](https://lists.openstreetmap.org/pipermail/talk-us/2017-October/017893.html)

![download](https://user-images.githubusercontent.com/120452/31143553-d5d193e4-a83a-11e7-847c-2f19bb294fc6.png)

Current guidance:

* For ways that don't have TWLTL tagging yet, use the plugin and the generic `lanes` / `turn:lanes` schema.
* Where (local) mappers have already added `centre_turn_lane` tagging, leave it alone.

Relates to #24 #5

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#11
