### ISSUE TITLE
[Phoenix] HOV lane editing

### ISSUE THREAD

**Issue by hoream-telenav** [TelenavMapping/mapping-projects#29]
### **Description:**
For this task we will map the lanes and turn lanes in Maricopa and Pinal County, Arizona. During this task we’ll plan to add also HOV lanes to offer a better guidance for routing. 
### **How to map:**
The **hov=*** tag is used to indicate vehicle occupancy requirements for a way.  If some lanes on the way are HOV restricted differently (for example, common on carriageways), **hov=***, if used, should be supplemented with **hov:lanes=*** for per-lane access and restrictions. 
### **Values for HOV tag:**
• designated: The way is designated to high occupancy vehicles.
• yes: High occupancy vehicles are allowed. This by itself does not imply that other vehicles are restricted from using the way. If is used, should be supplemented with **hov:lanes=***. 
• no: High occupancy vehicles are not allowed on the way. This by itself does not imply that other vehicle types can use it.
• **hov:minimum=*** Typical values for this key are 2 (for "2+" lanes), and 3 (for "3+" lanes).
• **lane:** **_Deprecated and nonstandard_**. If seen on a way, **this value should be removed**; instead, **hov:lanes=*** is the preferred tagging for HOV access restrictions per lane
![image](https://user-images.githubusercontent.com/25051328/31275625-b277b956-aaa0-11e7-820a-323ae8f972a8.png)
![image](https://user-images.githubusercontent.com/25051328/31275628-b632ad1c-aaa0-11e7-9ac5-39e7ec3e5e2e.png)

### **Examples of tagging scheme:**
![image](https://user-images.githubusercontent.com/25051328/31275879-b823af80-aaa1-11e7-8ba2-dd57ac0cfef8.png)

**References**
http://wiki.openstreetmap.org/wiki/Key:hov
https://www.tripsavvy.com/hov-lanes-2682151
http://www.mto.gov.on.ca/english/ontario-511/hov-lanes.shtml

**Comment by bogdanp-telenav** [comment]
During our build-up process in Phoenix we added about 200 miles of HOV lane info. 
![image](https://user-images.githubusercontent.com/21235765/42206428-bc109d96-7eaf-11e8-9f0c-36bc8217110c.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#10
