### ISSUE TITLE
USA – Detroit – Road geometry

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#3]
## Description
In this project we will map road geometry in Detroit, Michigan area and we will focus on adding missing roads as well as improving the existing data in OSM.
![missing](https://cloud.githubusercontent.com/assets/24428741/24806663/395690f4-1bbe-11e7-875e-420c5534e7e4.JPG)

## How to map
We will follow the mapping scheme that is already used in the United States as it is described on this page:
* https://wiki.openstreetmap.org/wiki/United_States_roads_tagging

For adding roundabouts we will follow this guideline :
* https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout
We’ll also keep in mind to add any other useful information that we have for the mapped road geometry (ex: road name, oneway tag, lanes).

## Sources
* Satellite imagery: Bing, Mapbox, NAIP
* Government data: TIGER Roads
* Improve OSM - Missing Roads
* Street-level imagery: OpenStreetCam, Mapillary
## See also
* https://www.mapbox.com/mapping/mapping-for-navigation/road-features-mapping-guide/#functional-road-class
* https://wiki.openstreetmap.org/wiki/Key:highway
* https://www.mapbox.com/mapping/becoming-a-power-mapper/fixing-common-mapping-issues/

**Comment by mvexel** [comment]
Which version of TIGER will we be using?

**Comment by manuelab-telenav** [comment]
We'll be using the latest version, released in 2016: https://www.census.gov/geo/maps-data/data/tiger.html

**Comment by mvexel** [comment]
(Just FYI new TIGER data versions are released annually around the end of the summer)

**Comment by jmcbroom** [comment]
For road geometry, might also want to consider the Michigan Geographic Framework: http://gis-michigan.opendata.arcgis.com/datasets/5fddb53b929b4b729b8d4282b4d23ade_20

I think that's v15 (for 2015) - not sure on the release schedule for v16.

**Comment by manuelab-telenav** [comment]
Great tip! Thanks, we'll be using these for sure.

**Comment by markscalf** [comment]
Please keep in mind that there has been a significant amount of construction in the area (and will continue to be), especially along freeways which may not be reflected in the latest Bing imagery (i.e. I 75 near bridge to Canada, I 275 between I96 & I 696, new 10 yr project along I75 between square lake road and downtown Detroit, new project along M59 between Romeo Plank and ~ Hayes).  All road alignment changes should be confirmed with either probe traces and/or open source imagery traces from Mapillary and/or OpenStreetCam.

**Comment by markscalf** [comment]
Another thing to point out is that there are a significant number of duplicate nodes (i.e. highway node shared with admin boundary).  I believe this issue goes back to initial import and is common throughout the entire metro area.  Recommend that these be corrected if seen while adjusting road geometry.

**Comment by simonap-telenav** [comment]
Thanks, that's very helpful. We've found a few cases of duplicated nodes and we corrected them. We'll keep in mind your recommendations when we're editing.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#22
