### ISSUE TITLE
[Phoenix] - Turn restrictions editing

### ISSUE THREAD

**Issue by hoream-telenav** [TelenavMapping/mapping-projects#37]
Our team will map turn restrictions in Phoenix area and we will focus on adding new turn restrictions as well as correcting the existing ones that need it.

**How to map**
We will follow the mapping scheme that is already used by OSM community as it is described on this page: http://wiki.openstreetmap.org/wiki/Relation:restriction.

**Sources:**
Open Street Cam, Mapillary imagery and Mapillary object layer

**Tags that we use for mapping:**
![image](https://user-images.githubusercontent.com/25051328/32220453-67daf59a-be3a-11e7-8a82-d777e94730fa.png)

**Comment by andreis-telenav** [comment]
We worked on this issue for 3 months, starting from November. We succeeded to review a large amount of intersections between motorway, trunk, primary, secondary, tertiary, residential and service ways from Phoenix area.

During our project we accomplished:
•	to add new turn restrictions
•	to correct some of the damaged ones
•	to remove some of the wrong ones.

In the first part of our project we looked over 1723 turn restriction signs identified in Open Street Cam.

![1](https://user-images.githubusercontent.com/24649912/34869895-1cf86e8c-f791-11e7-9cc9-e4d0858e2970.jpg)

In the second part, we managed to find turn restriction signs also based on Mapillary Imagery and Mapillary Object Layer.

All the turn restriction signs summed in the end 3289, from which 350 turned to be missing from Open Street Map.

Bellow, you can see a chart pie with our work.

![2](https://user-images.githubusercontent.com/24649912/34869858-0436e798-f791-11e7-9498-72089e7f2f80.jpg)

During this task we also reviewed 11932 and added 376 new traffic lights.

The heatmap bellow represents all the turn restriction edits of our team, from November till now, in the area of Phoenix. Darker colors indicate high density and brighter colors low density.

![3](https://user-images.githubusercontent.com/24649912/34869947-48939490-f791-11e7-870e-f6a62422a50f.jpg)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#3
