### ISSUE TITLE
USA – Detroit – Road name

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#4]
## Description
In this project we will map road name in Detroit, Michigan area and we will focus on adding missing names as well as improving the existing data in OSM.
![name](https://cloud.githubusercontent.com/assets/24428741/24807273/48bb8124-1bc0-11e7-8630-c77bdb0559be.JPG)

## How to map
We will follow the mapping scheme that is already used in the United States as it is described on this page:
* https://wiki.openstreetmap.org/wiki/United_States_roads_tagging

For name tags we will follow this guideline:
* https://wiki.openstreetmap.org/wiki/Names 

We will consult the [Wiki US Roads Project](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_U.S._Roads ) for naming conventions.
## Sources
* Government data: TIGER roads
* [Local data](https://wiki.openstreetmap.org/wiki/Potential_Datasources#Michigan)
## Who will be involved?
Telenav mapping team with the following usernames: [alinan_telenav](https://www.openstreetmap.org/user/alinan_telenav), [gabis_telenav](https://www.openstreetmap.org/user/gabis_telenav), [andreis_telenav](https://www.openstreetmap.org/user/andreis_telenav), [simonap_telenav](https://www.openstreetmap.org/user/simonap_telenav), [hoream_telenav](https://www.openstreetmap.org/user/hoream_telenav).
## See also:
* https://mapzen.com/blog/targeted-editing-no-name-roads/ 
* https://github.com/mapbox/mapping/issues/100

**Comment by skylerbunny** [comment]
You may wish to also check out Michigan specific mapping suggestions/editor best practices, which are located here: https://wiki.openstreetmap.org/wiki/Michigan

There is discussion about relations and the standards in the state where they may differ.

**Comment by manuelab-telenav** [comment]
We started editing road geometry and road names on Detroit area and we’ve encountered some particular cases with the street names and name suffixes and we were not sure what to do in these situations.

1. Location 42.138179, -83.190357 

- in OSM, the road name is Trumbull Street
- in Tiger Roads 2016 file and [local data](https://gis-michigan.opendata.arcgis.com/datasets/5fddb53b929b4b729b8d4282b4d23ade_20) the name is Trumbull Avenue
There are a lot of cases like this one so we wanted to be sure that it’s ok if we modify them based on the.

**Comment by skylerbunny** [comment]
Something I'd probably try is some searches with the US Zip Code Lookup: https://tools.usps.com/go/ZipLookupAction, using a known address number for the street in question, and try iterations of the road name. When the one represented by the official postal address is hit, you'll get a Zip+4 result. The main point of course is that it's just told you what 'an official postal address for an address on the street' is.

**Comment by DougPeterson** [comment]
The lack of Avenue, Road or Street on street signs is pretty common.  As such, more than one will be in use or on the map.  That is the case with my street and street sign.  It only says Oakland.  It should say Oakland Avenue.  That is what was switched to back in the 1950s as noted in a newspaper article from then.  The city refers to it as Oakland Street.  It remains Oakland Avenue on the property tax record.  I usually consult property tax information and treat that as the authority.

**Comment by hoream-telenav** [comment]
@skylerbunny @DougPeterson thanks for your suggestions; we will analyze them and make a research on it to see how it can help us and community

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#21
