### ISSUE TITLE
[Ecuador] Adding the network tag to route relations

### ISSUE THREAD

**Issue by arming-telenav** [TelenavMapping/mapping-projects#42]
### **Description**

The main objective of the project is to improve the OSM quality of minor and major from Ecuador by adding the missing relations to OSM and editing the existing ones. We focused on the minor and major routes described [here](https://en.wikipedia.org/wiki/Highways_in_Ecuador). 

After editing the routes, we observed that almost all of **them lack the network tag** which is crucial for an complete navigation experience. Based on this we started a research in the nearby countries (Argentina, Bolivia, Chile, Columbia, Peru) and studied the OSM data from existing route relations. After thoughtful consideration the network tag that we propose is:
- for major routes (most important roads) the network tag will be: **EC:national**
- for minor routes (least important roads) the network tag will be: **EC:provincial**

### **Feedback**
If you have questions or any other feedback related to this topic please let us know.

**Comment by hoream-telenav** [comment]
Based on our research in the nearby countries (Argentina, Bolivia, Chile, Columbia, Peru) and studied the OSM data from existing route relations, we added network tag for major routes (**network tag: EC:national**) and for minor routes (**network tag: EC:provincial**).
![image](https://user-images.githubusercontent.com/25051328/37711565-d2c70116-2d19-11e8-8903-18f84b6f9cd6.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Ecuador_mapping_projects#1
