### ISSUE TITLE
US-Build up project- Dallas

### ISSUE THREAD

**Issue by hoream-telenav** [TelenavMapping/mapping-projects#45]
In this project, our team will edit in Dallas area

![image](https://user-images.githubusercontent.com/25051328/35574224-e2fd0f30-05e1-11e8-9aba-4c2bcd4c4aa1.png)
     The features of interest will be: **road geometry, road name, one ways, turn restrictions, signpost**.
     For the **road geometry** will add new roads and correct the existing ones if is need using the following sources: Bing imagery, Digital Globe imagery, Open Street Cam, Mapillary, Tiger Roads 2017 (also used for editing road name), Improve OSM and local imagery such as Texas Orphophoto. To make sure about the quality of the area reviewed, will use Validation Tool and Keep Right Tool.
     For **road name**, we received approval to use the data from: http://www.collincountytx.gov/gis_rural_addressing/Pages/downloads.aspx and 
https://dentoncounty.com/Departments/Technology-Services/Geographic-Information-Systems/Download-Geographic-Data.aspx
     The **one ways** will be edited based on Improve OSM data but also using Open Street Cam, Mapillary and imagery.
     For editing **turn restrictions**, our main sources will be Open Street Cam, Mapillary map object and Improve OSM.
     The **signpost** will be added using Open Street Cam and Mapillary.
     For these features, we use the following resources:
For **road geometry**:
•	https://www.mapbox.com/mapping/mapping-for-navigation/road-features-mapping-guide/#functional-road-class
•	https://wiki.openstreetmap.org/wiki/Key:highway
•	https://www.mapbox.com/mapping/becoming-a-power-mapper/fixing-common-mapping-issues/
•	https://wiki.openstreetmap.org/wiki/Key:oneway
•	https://wiki.openstreetmap.org/wiki/Key:barrier
For **turn restrictions**:
•	http://wiki.openstreetmap.org/wiki/Relation:restriction
•	https://www.mapbox.com/mapping/mapping-for-navigation/adding-turn-restrictions/ 
For **signpost**:
•	https://wiki.openstreetmap.org/wiki/Key:destination 
•	https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/ 

The edits in this areas will be made by:
•	arming_telenav
•	bogdanp_telenav
•	georges_telenav
•	ioanam_telenav
•	marianp_telenav
•	valdm_telenav
•	oanac2_telenav
•	istvanv_telenav
•	biancah_telenav
•	catalinad_telenav
•	hoream_telenav
•	ionutr_telenav
•	lacramioaram_telenav
•	mihaii_telenav
•	lorandr_telenav
•	andreis_telenav
•	teodorab_telenav

**Comment by mihaii-telenav** [comment]
In the past couple of months the Telenav Mapping team has been working in improving OSM around Dallas - Fort Worth area. Here are the counties of interest:

- Denton
- Collin
- Tarrant
- Dallas
- Rockwall

As mentioned in the previous post, we focused on the following map features:

- Road geometry
- Route relations
- Road name
- Oneway
- Turn restrictions
- Signposts

You can find below statistics regarding our work:

### **Road geometry**
- Reviewed **13,020 mi**
- Edited **2,382 mi**

### **Route relations**
- identified and fixed **95** route relations, using [Relation Analyzer
](http://ra.osmsurround.org/)

### **Road name**
- Reviewed **1,250 mi**
- Edited **483 mi**

### **Oneway**
- Reviewed **284** tiles from ImproveOSM
- Edited **73** tiles

### **Turn restrictions**
- Reviewed **7373** locations with OpenStreetCam and Mapillary
- Edited **468** locations

### **Signposts**
- Reviewed **955** locations with OpenStreetCam and Mapillary
- Edited **466** locations

### Overview of all our edits

![image](https://user-images.githubusercontent.com/20751382/37827308-9f9e00a0-2e9f-11e8-86f8-9d512861fec3.png)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#6
