### ISSUE TITLE
USA – Detroit – Lanes

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#5]
## Description
This project is designed to improve the quality of OSM by adding and updating lanes and turn lanes on motorways, motorway_links, trunks and trunk_links, in Detroit, Michigan.
![lanes](https://cloud.githubusercontent.com/assets/24428741/24857606/94d4a602-1df1-11e7-8ae0-78fe48b5415c.png)

## How to map
For editing lanes and turn lanes we will use **JOSM**, the [**TurnLanes-tagging Editor**](https://www.mapbox.com/blog/turn-lanes-mapping/) plugin and the **Lane and road attributes** map paint style. 
We will use the **‘lanes=\*’** tag to add the number of lanes on every way as it is described [here](http://wiki.openstreetmap.org/wiki/Lanes).
For the direction in which a lane will lead we will use the **‘turn:lanes=*’** tag as it is described [here](http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane).

## Sources
* **Aerial Imagery**: Bing, Mapbox, NAIP, Digital Globe
* **Street level imagery**: OSC, Mapillary
## Who will be involved
[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team) 

## See also
http://wiki.openstreetmap.org/wiki/Lanes
http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane
https://github.com/JOSM/turnlanes-tagging
https://www.mapbox.com/blog/turn-lanes-mapping/

**Comment by markscalf** [comment]
Mapbox did a significant amount of turn lane editing in Detroit last summer which requires clean-up; specifically along Michigan Ave in Dearborn/Detroit. Here is an example where their edits were incorrect:  http://osm.org/go/ZXCnp6GDB?m=

Lane count is wrong and the turn lanes are not fully mapped.  
Lanes:foward = 3
Lanes:backwards = 4
turn:lanes:backward = left|||right

**Comment by andreis-telenav** [comment]
Hello @markscalf ,
Thank you for your advice. For now, we are focused only on motorways, motorway_links, trunks and trunk_links. We used also Mapillary and OSC in our edits, but from now on we'll pay more attention to them. 
If you have any other suggestions or if you'll find any mistakes in our edits please let us know.

**Comment by manuelab-telenav** [comment]
We started editing lanes in Detroit area and we’ve encountered some cases where we are not sure how to add lane number.
In the examples below, how many lanes do we have between the red lines? IWhere should we split the road when adding lane numbers? Is it ok to split them where the red lines indicate?

### 1. Location: 42.6025814, -83.023706
![l1](https://cloud.githubusercontent.com/assets/24428741/25281666/b2c305aa-26b6-11e7-8988-0ec2b07fc966.png)

### 2. Location: 42.553038, -82.872834
![l2](https://cloud.githubusercontent.com/assets/24428741/25281697/ce257922-26b6-11e7-9fff-bc90bf1a6839.png)

**Comment by manuelab-telenav** [comment]
#### This is how we map lanes (42.474427, -83.155894):

![1](https://cloud.githubusercontent.com/assets/24428741/25706541/66f53c82-30e9-11e7-8f5c-ca442f041ca4.jpg)
* Move motorway_junction to postion 2 (usually where continuous line begins)
* Split way between 1 and 2; add lanes=5 on motorway
* Split way between 2 and 3; add lanes=4 on motorway and lanes=1 on motorway_link
* After 3, add on motorway lanes=4
 
If you have any suggestions or comments, we are happy to learn from them.

**Comment by manuelab-telenav** [comment]
We worked on this issue for 2 months and succeeded to review a large part of motorway, trunk, primary and secondary roads from Detroit area, in order to add or update lane info.

During this project, we managed to review 3100 miles and edit 1730 miles of roads.

![image](https://user-images.githubusercontent.com/24428741/28417696-b8152c08-6d61-11e7-9dcf-e6ece795ac98.png)


![image](https://user-images.githubusercontent.com/24428741/28417358-8b72436c-6d60-11e7-89f2-b950e3a6d7ce.png)

Here’s how the number of miles of roads with lane information has increased during the project:
![image](https://user-images.githubusercontent.com/24428741/28417734-d2216bc0-6d61-11e7-996f-4928c14cd66b.png)


The edits we made cover a large area of the Wayne, Macomb and Oakland counties. In the GIF below you can see an evolution (difference between March and July) of our lane info edits in Open Street Map .

![1 lanes_diff](https://user-images.githubusercontent.com/24428741/28417426-c0391742-6d60-11e7-8878-efbb97b72742.gif)

Some edits in Detroit downtown, from April until July:

![2 lanes_wayne](https://user-images.githubusercontent.com/24428741/28417440-cb3d11ac-6d60-11e7-840f-ba5f5a1bcfb0.gif)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#20
