### ISSUE TITLE
[Canada] Malformed restrictions that prevent legal routing

### ISSUE THREAD

**Issue by mvexel** [TelenavMapping/mapping-projects#6]
As reported on `talk-ca`. No specific changesets mentioned.

**Comment by mvexel** [comment]
Reported on `talk-ca`: 

> malformed restrictions that prevent legal routing

No specific changesets mentioned. Requesting more details.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#10
