### ISSUE TITLE
[Canada] "Implicit" turn restrictions

### ISSUE THREAD

**Issue by mvexel** [TelenavMapping/mapping-projects#8]
This issue was raised on `talk-ca` a few weeks ago. 

[Example relation](https://www.openstreetmap.org/relation/7096540)

![screenshot 2017-04-25 23 08 03](https://cloud.githubusercontent.com/assets/120452/25416492/129fa516-2a0c-11e7-90a9-a560aa3376a4.jpg)

These are turn restrictions that are not signed but identify turns that are either not allowed through general traffic rules or physically impossible or dangerous to make.

**Comment by mvexel** [comment]
Current status:

* There is no consensus that this type of restriction is appropriate to put in OSM.
* We halted mapping these types of turn restrictions until we have more clarity.

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#8
