### ISSUE TITLE
[MapRoulette] Missing road names in Jacksonville, FL from TIGER 2017 data

### ISSUE THREAD

**Issue by mihaii-telenav** [TelenavMapping/mapping-projects#83]
This challenge focuses on adding missing road names in the Jacksonville, FL metro area, using TIGER 2017 processed data.
## **Challenge link**
http://maproulette.org/mr3/challenge/3041

## **Data source**
[TIGER](https://www.census.gov/geo/maps-data/data/tiger.html)

## **Data license**
Public data

## **Data processing**
The data was processed using [Cygnus+](http://cygnus.improve-osm.org/add;jsessionid=1ql3qs02h8wl01fqc0de6ewfu8?0), in order to obtain the road names that were missing from OSM but existed in TIGER 2017 data

## **Editing workflow**
Select a task from MapRoulette and open it in JOSM. It is recommended to always open the task in a new JOSM layer, so that the risk of an edit conflict to appear is minimized.

![image](https://user-images.githubusercontent.com/20751382/41140240-d6802c1a-6af4-11e8-94dc-a4bb25052cd5.png)

Once you've successfully added the road name, hit the upload button in JOSM to commit the edit. Note that MapRoulette will automatically add the local data source from where the name was taken.

![image](https://user-images.githubusercontent.com/20751382/41140387-f09bfb78-6af5-11e8-86dc-b6cbd15b49ee.png)

Next step is to select a task status in MapRoulette so that other people can see that the task has been reviewed, and will not appear anymore.

![image](https://user-images.githubusercontent.com/20751382/41140410-12a1772a-6af6-11e8-9147-25b6a50e502a.png)

**Comment by mihaii-telenav** [comment]
This challenge has been completed! Please find below the numbers:

Challenge published - **June 8th, 2018**
Challenge completed - **June 12th, 2018**

Task statuses:

- Total # of tasks - **273**
- Fixed - 200 - **73%**
- Already fixed - 47 - **17%**
- Too hard - 25 - **9%**
- Not an issue - 1 - **<1%**

### Leaderboard
Gold medal - [**xujiayi_1256**](https://www.openstreetmap.org/user/xujiayi_1256)
Silver medal - [**shawat94**](https://www.openstreetmap.org/user/shawat94)
Bronze medal - **[kfremd](https://www.openstreetmap.org/user/kfremd)**

Excellent work!

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Community_MapRoulette#11
