### ISSUE TITLE
[Canada] Replacing replacing on-the-ground mapping with Bing / Geobase based edits

### ISSUE THREAD

**Issue by mvexel** [TelenavMapping/mapping-projects#9]
This was called out on `talk-ca`. No specific examples given.

> [...] replacing my on-the-ground mapping with their own based solely on out-of-date imagery or the often-questionable Geobase [...]

**Comment by scruss** [comment]
Andrew gave a specific example of this last month (now reverted by him):
https://overpass-api.de/achavi/?changeset=46740353#map=16
as discussed in 
https://lists.openstreetmap.org/pipermail/talk-ca/2017-March/007793.html

**Comment by mvexel** [comment]
Thanks @scruss -- we'll investigate how to best follow up on this.

**Comment by inah-telenav** [comment]
Regarding this issue, when is the case we only smooth the road geometry we do not align it with Geobase Roads

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/Canada-mapping-projects#7
